# Generated by Django 5.0.4 on 2024-04-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_enry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enry',
            new_name='Entry',
        ),
    ]
